//made by Jack Legate
public class ThreeHeads 
{

	public static void main(String[] args) 
	{
		
		boolean exit = false;
		int count = 0;
		int coin = 0;
		
		while (!exit) 
		{
			
			coin = (int)(Math.random() * 2);
			
			if(coin == 1) 
			{
				System.out.print("H ");
				count++;
			} 
			else 
			{
				System.out.print("T ");
				count = 0;
			}
			
			if(count == 3) 
			{
				exit = true;
			}
		}
		
		System.out.print("\nCongrats!");
	}

}
